config/routes.rb
BaseApp::Application.routes.draw do
  resources :usuarios
  resources :sesiones, only: [:new, :create, :destroy]
  resources :mensajes, only: [:create, :destroy]
  root 'paginas_estaticas#inicio'
  match '/registro',  to: 'usuarios#new', via: 'get'
  match '/iniciases', to: 'sesiones#new', via: 'get'
  match '/cierrases', to: 'sesiones#destroy', via: 'delete'
  match '/ayuda', to: 'paginas_estaticas#ayuda', via: 'get'
  match '/acercade', to: 'paginas_estaticas#acercade', via: 'get'
  match '/contacto', to: 'paginas_estaticas#contacto', via: 'get'

  

end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
	belongs_to :usuario
	default_scope -> { order('created_at DESC') }
	validates :contenido, presence: true, length: { maximum:250 }
	validates :usuario_id, presence: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :mensajes, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :nombre, presence: true, length: { maximum: 50 }
	VALIDA_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/
	validates :email, presence: true, format: { with: VALIDA_EMAIL },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 8 }

	def Usuario.new_token_recuerdo
      SecureRandom.urlsafe_base64
  	end

  	def Usuario.digest(token)
      Digest::SHA1.hexdigest(token.to_s)
  	end

  	def muro
  		Mensaje.where("usuario_id = ?", id)
    end

private

    def create_token_recuerdo
      self.token_recuerdo = Usuario.digest(Usuario.new_token_recuerdo)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SesionesHelper
end

app/controllers/mensajes_controller.rb
#encoding: UTF-8

class MensajesController < ApplicationController
	before_action :usuario_logueado, only: [ :create, :destroy]
	before_action :usuario_valido,   only: :destroy

	def create
		@mensaje = usuario_actual.mensajes.build(mensaje_params)
		if @mensaje.save
			flash[:success] = "¡Mensaje creado!"
			redirect_to root_url
		else
			@items_muro = []
			render 'paginas_estaticas/inicio'
		end
	end
	
	def destroy
		@mensaje.destroy
		redirect_to root_url
	end


	private

	def mensaje_params
		params.require(:mensaje).permit(:contenido)
	end

	def usuario_valido
		@mensaje = usuario_actual.mensajes.find_by(id: params[:id])
		redirect_to root_url if @mensaje.nil?
	end
end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  
  def inicio
    if inicio_sesion?
      @mensaje = usuario_actual.mensajes.build
      @items_muro = usuario_actual.muro.paginate(page: params[:page])
    end
  end

  def ayuda
  end

  def acercade
  end

  def prueba
  end

  def contacto
  end
end

app/controllers/sesiones_controller.rb
#encoding: utf-8
class SesionesController < ApplicationController

	def new
	end

	def create	
	  	usuario = Usuario.find_by(email: params[:sesion][:email].downcase)
	  	if usuario && usuario.authenticate(params[:sesion][:password])
	  		inicia_sesion usuario
	  		redirige_antes usuario
	  	else
	  		flash.now[:error] = "Revisa que tu email y contraseña sean correctos"
	  		render 'new'
	  	end
	end

	def destroy	
	  cerrar_sesion
	  redirect_to root_url	
	end
end
 

app/controllers/usuarios_controller.rb
#encoding: UTF-8
class UsuariosController < ApplicationController
  before_action :usuario_logueado, only: [:index, :edit, :update, :destroy]
  before_action :usuario_valido,   only: [:edit, :update]
  before_action :usuario_admin,    only: :destroy

  def index
    @usuarios = Usuario.paginate(page: params[:page])
  end

  def show
    @usuario = Usuario.find(params[:id])
    @mensajes = @usuario.mensajes.paginate(page: params[:page])
  end

  def new
  	@usuario = Usuario.new
  end

  def create
  	@usuario = Usuario.new(usuario_params)
  	if @usuario.save
      inicia_sesion @usuario
      flash[:success] = "Te has registrado con éxito: #{@usuario.nombre}!"
      redirect_to @usuario
  	else
  		render 'new'
  	end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(usuario_params)
      flash[:success] = "Perfil actualizado"
      redirect_to @usuario
    else
      render 'edit'
    end
  end

  def destroy
    Usuario.find(params[:id]).destroy
    flash[:success] = "Usuario eliminado"
    redirect_to usuarios_url
  end
  
  private

  def usuario_params
  	params.require(:usuario).permit(:nombre, :email, :password, :password_confirmation)
  end 

  #filtros

  def usuario_valido
    @usuario = Usuario.find(params[:id])
    redirect_to(root_url) unless usuario_actual?(@usuario)      
  end

  def usuario_admin
    redirect_to(root_url) unless usuario_actual.admin?
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper

	def titulo_base(titulo_pagina)
		titulo = "Mi aplicación"
		if titulo_pagina.empty?
			titulo
		else
			"#{titulo} | #{titulo_pagina}"
		end
	end
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/helpers/sesiones_helper.rb
#encoding: UTF-8
module SesionesHelper

  def inicia_sesion(usuario)
    token_recuerdo = Usuario.new_token_recuerdo
    cookies.permanent[:token_recuerdo] = token_recuerdo
    usuario.update_attribute(:token_recuerdo, Usuario.digest(token_recuerdo))
    self.usuario_actual = usuario
  end

  def inicio_sesion?
  	!usuario_actual.nil?
  end

  def usuario_actual=(usuario)
    @usuario_actual = usuario
  end

  def usuario_actual
  	token_recuerdo = Usuario.digest(cookies[:token_recuerdo])
    @usuario_actual ||= Usuario.find_by(token_recuerdo: token_recuerdo)
  end

  def usuario_actual?(usuario)
    usuario == usuario_actual
  end

  def usuario_logueado 
    unless inicio_sesion?
      guardar_ubicacion
      redirect_to iniciases_url, notice: "Por favor, inicia sesión"
    end
  end    

  def cerrar_sesion
    usuario_actual.update_attribute(:token_recuerdo, 
                                    Usuario.digest(Usuario.new_token_recuerdo))
    cookies.delete(:token_recuerdo)
    self.usuario_actual = nil
  end

  def redirige_antes(default)
    redirect_to(session[:anterior_a] || default)
    session.delete(:anterior_a)
  end

  def guardar_ubicacion
    session[:anterior_a] = request.url if request.get?
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper

	#Implementación de la imagen de perfil, usando Gravatar
	def gravatar_de(usuario)
		gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: usuario.nombre, class: "gravatar_imagen")
	end
end

app/views/layouts/_etiquetaFooter.html.erb
<footer class="footer">
  Aplicación creada en <a href="http://rubyonrails.org/">Ruby on Rails.</a>
  <nav>
    <ul>
      <li><%= link_to "Acerca De",   acercade_path %></li>
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><a href="http://rubyonrails.org/">¿Qué hay de nuevo en Rails?</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_etiquetaHeader.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Mi Aplicación", root_path, id: "encabezado" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Inicio",    root_path %></li>
          <li><%= link_to "Ayuda",    ayuda_path %></li>
          <% if inicio_sesion? %>
            <li><%= link_to "Usuarios", usuarios_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cuenta<b class="caret"></b>
              </a>
               <ul class="dropdown-menu">
                <li><%= link_to "Perfil", usuario_actual %></li>
                <li><%= link_to "Configuración", edit_usuario_path(usuario_actual) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Cerrar sesión", cierrases_path, method: "delete" %>
                </li>
              </ul>
              </li>
          <% else %>
          <li><%= link_to "Entrar", iniciases_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= titulo_base(yield(:titulo)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/etiquetaHeader'%>
    <div class="container">
    <% flash.each do |clave, valor| %>
      <div class="alert alert-<%= clave %>"><%= valor %></div>
    <% end %>
      <%= yield %>
      <%= render 'layouts/etiquetaFooter' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/mensajes/_mensaje.html.erb
<li>
	<span class="contenido"><%= mensaje.contenido %></span>
	<span class="timestamp">
		Creado hace <%= time_ago_in_words(mensaje.created_at) %>.
	</span>
	<% if usuario_actual?(mensaje.usuario) %>
		<%= link_to "eliminar", mensaje, method: :delete,
		data: { confirm: "¿Estás seguro?" },
		title: mensaje.contenido %>
	<% end %>
</li>

app/views/paginas_estaticas/acercade.html.erb
<% provide(:titulo, 'Acerca De')%>
<h1>Acerca De</h1>
<p>
  Esta página tendrá en el futuro, información sobre la aplicación
</p>

app/views/paginas_estaticas/ayuda.html.erb
<% provide(:titulo, 'Ayuda')%>
<h1>Ayuda</h1>
<p>
  Esta es la página de prueba para las vistas de mi aplicación.
  Para obtener ayuda sobre Ruby on Rails, puedes visitar:
  <a href="http://rubyonrails.org"></a>
</p>

app/views/paginas_estaticas/contacto.html.erb
<% provide(:title, 'Contacto') %>
<h1>Contacto</h1>
<p>
  Página de contacto para el desarrollador del proyecto.
</p>

app/views/paginas_estaticas/inicio.html.erb
<% if inicio_sesion? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/datos_usuario' %>
			</section>
			<section>
				<%= render 'shared/form_mensaje' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Muro de mensajes</h3>
			<%= render 'shared/muro' %>
		</div>
	</div>
<% else %>

	<div class="center hero-unit">

		<h1>Mi Aplicación</h1>
		<h2>Esta página es el comienzo de una aplicación sencilla pero que en un futuro crecerá</h2>
		<p>
		    Esta es la página de prueba para
  			las vistas de mi aplicación
		</p>
<%= link_to "¡Registrate, es rápido y fácil!", registro_path, class: "btn btn-large btn-primary" %>
	</div>

<%= link_to image_tag("rails_icono.png", alt: "Rails Icono"), 'http://rubyonrails.org/' %>
<% end %>

app/views/paginas_estaticas/prueba.html.erb
<h1>Prueba</h1>
<p>
  Esta página sirve de ejemplo para
  verificar que se añadió una 
  página manualmente a nuestra
  aplicación. :)
</p>

app/views/sesiones/new.html.erb
<% provide(:titulo, 'Inicio de sesión') %>
<h1>Iniciar sesión</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(:sesion, url: sesiones_path) do |atributo| %>

      <%= atributo.label :email %>
      <%= atributo.text_field :email %>

      <%= atributo.label :password %>
      <%= atributo.password_field :password %>

      <%= atributo.submit "Inicia sesión", class: "btn btn-large btn-primary" %>
    <% end %>

    <p>¿No tienes cuenta? 
	   <br><%= link_to "¡Registrate ahora!", registro_path %></br>
    </p>
  </div>
</div>

app/views/shared/_datos_usuario.html.erb
<%= link_to gravatar_de(usuario_actual), usuario_actual %>
<h1>
	<%= usuario_actual.nombre %>
</h1>
<span>
	<%= link_to "Mi perfil", usuario_actual %>
</span>
<span>
	<%= pluralize(usuario_actual.mensajes.count, "mensajes") %>
</span>

app/views/shared/_form_mensaje.html.erb
<%= form_for(@mensaje) do |atributo| %>
	<%= render 'shared/mensajes_error', object: atributo.object %>
		<div class="field">
			<%= atributo.text_area :contenido, placeholder: "Escribe lo que piensas..." %>
		</div>
	<%= atributo.submit "Enviar", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_item_muro.html.erb
<li id="<%= item_muro.id %>">
	<%= link_to gravatar_de(item_muro.usuario), item_muro.usuario %>
	<span class="usuario">
		<%= link_to item_muro.usuario.nombre, item_muro.usuario %>
	</span>
	<span class="contenido"><%= item_muro.contenido %></span>
	<span class="timestamp">
		Creado hace <%= time_ago_in_words(item_muro.created_at) %>.
	</span>
	<% if usuario_actual?(item_muro.usuario) %>
		<%= link_to "eliminar", item_muro, method: :delete,
		data: { confirm: "¿Estás seguro?" },
		title: item_muro.contenido %>
<% end %>
</li>

app/views/shared/_mensajes_error.html.erb
<% if object.errors.any? %>
  <div id="errores_estilo">
    <div class="alert alert-error">
      <% if object.errors.count == 1 %>
         Existe 1 error
      <% else %>
      	 Existen <%= object.errors.count %> errores
      <% end %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
        <% if msg == "Nombre can't be blank" %>
             <li>* <%= "Debes llenar el campo con tu nombre" %></li>
        <% elsif msg == "Email can't be blank" %>
             <li>* <%= "Debes llenar el campo con tu correo electrónico (email)" %></li>
        <% elsif msg == "Email is invalid" %>
             <li>* <%= "El correo electrónico que proporcionaste no es válido" %></li>
        <% elsif msg == "Password can't be blank" %>
             <li>* <%= "La contraseña no puede ser vacía" %></li>
        <% elsif msg == "Password is too short (minimum is 8 characters)" %>
             <li>* <%= "La longitud mínima para la contraseña es de 8 caracteres" %></li>
        <% elsif msg == "Password confirmation doesn't match Password" %>
             <li>* <%= "La contraseña no coincide" %></li>
        <% elsif msg == "Email has already been taken" %>
             <li>* <%= "El correo ya está registrado" %></li>
        <% end %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_muro.html.erb
<% if @items_muro.any? %>
	<ol class="mensajes">
		<%= render partial: 'shared/item_muro', collection: @items_muro %>
	</ol>
<%= will_paginate @items_muro %>
<% end %>

app/views/usuarios/_usuario.html.erb
<li>
      <%= gravatar_de usuario %>
      <%= link_to usuario.nombre, usuario %>
      
      <% if usuario_actual.admin? && !usuario_actual?(usuario) %>
      	| 
      <%= link_to "eliminar", usuario, method: :delete, data: { confirm: "¿Seguro que deseas eliminar al usuario?" } %>
      <% end %>
</li>

app/views/usuarios/edit.html.erb
<% provide(:titulo, "Editar usuario") %>
<h1>Actualiza tu perfil</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@usuario) do |atributo| %>
      <%= render 'shared/mensajes_error', object: atributo.object %>

      <%= atributo.label :nombre %>
      <%= atributo.text_field :nombre %>

      <%= atributo.label :email %>
      <%= atributo.text_field :email %>

      <%= atributo.label :password %>
      <%= atributo.password_field :password %>

      <%= atributo.label :password_confirmation, "Confirmación" %>
      <%= atributo.password_field :password_confirmation %>

      <%= atributo.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_de @usuario %>
    <a href="http://gravatar.com/emails">Cambiar imagen</a>
  </div>
</div>

app/views/usuarios/index.html.erb
<% provide(:titulo, 'Todos los usuarios') %>
<h1>Listado de usuarios</h1>

<%= will_paginate %>

<ul class="listaUsuarios">
     <%= render @usuarios %>
</ul>

<%= will_paginate %>

app/views/usuarios/new.html.erb
<% provide(:titulo, 'Registro') %>
<h1>Registro</h1>

<div class = "row">
  <div class = "span6 offset3">
    <%= form_for(@usuario) do |atributo| %>
      <%= render 'shared/mensajes_error', object: atributo.object %>
      
    	<%= atributo.label :nombre %>
    	<%= atributo.text_field :nombre %>

    	<%= atributo.label :email %>
    	<%= atributo.text_field :email %>

    	<%= atributo.label :password %>
    	<%= atributo.password_field :password %>

    	<%= atributo.label :password_confirmation, "Confirmación de password" %>
    	<%= atributo.password_field :password_confirmation %>

    	<%= atributo.submit "¡Crear tu cuenta!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
 </div>

app/views/usuarios/show.html.erb
<% provide(:titulo, @usuario.nombre) %>

<div class = "row">
	<aside class = "span4">
		<section>
			<h1>
			  <%= gravatar_de @usuario %>
			  <%= @usuario.nombre %>
			</h1>
		</section>
	</aside>
	<div class="span8">
		<% if @usuario.mensajes.any? %>
			<h3>Mensajes (<%= @usuario.mensajes.count %>)</h3>
			<ol class="mensajes">
				<%= render @mensajes %>
			</ol>
			<%= will_paginate @mensajes %>
		<% end %>
	</div>
</div>